### PR TITLE
Sequential with parallel

### PR DESCRIPTION
**Pull request by m-giraud**
list of changes:
1. Using the python class 'RichardsNoMPIWrapper' forces the Dune solver tu run sequentially, even when DuMux compiled with MPI. ATT! only works for FOAMGrid (i.e., 1D models): MPI was not implemented for FOAMGrid, so grid->comm() is a dummy communication manager. For SPGrid (3D model): Maybe the grid creation function could also be adapted to allow us to select at runtime which communication manager to use. Currently not needed.
2. Adapt the setBC() functions. Now if the problem was not initialized, the BC are written in the parameter tree. Otherwise, the values in the vector are directly changed. Therefore, setBotBC, setTopBC, setSBotBC, setSTopBC should always work. Same for over functions defining BCs (setInnerFluxCyl, setInnerMatricPotential...).
3. Now two different functions: checkGridInitialized() and checkProblemInitialized() instead of checkInitialized()
4. solverbase::_map() can return array of shape (N,) instead of (N,1)

### CODE REVIEW

**Comment by m-giraud** [comment]
test the setup by running:
dumux-rosi/python/coupled_rhizo$ mpirun -n 4 python3 coupled_mai.py

**Comment by m-giraud** [comment]
some inner dumux functions call directly "Dune::MPIHelper::getCollectiveCommunication()" (see dumux  'io' folder) or get their communication manager from somewhere else, so we could get problem later depending on the functions used.

**Comment by timokoch** [comment]
@m-giraud you could report this in dumux because I don’t think dumux should do this

**Comment by m-giraud** [comment]
> @m-giraud you could report this in dumux because I don’t think dumux should do this

@timokoch  Could you precise what you mean by 'this'? to be sure of the information to send to the dumux team.

**Comment by timokoch** [comment]
Using MPIHelper::getColCom inside classes/function without possibility to change the communicator. Not sure what the problem with the newton is. but if there is an issue from your side just bring it up as an issue in dumux.

**Pull request merged**
